### ISSUE TITLE
Unable to configure ssh connection to gerrit using private key

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#1]
While, `Gerrit Trigger` is able to properly communicate using SSH with Gerrit, the new `gerrit-plugin` fails, mainly because it seems to fail to be able to use private keys for authentication.

The `git` version installed on Jenkins master is `1.8.3.1` and we have no control over it, this being provided as a managed Jenkins deployment.

I checked and `ssh` is able to establish connection to Gerrit but `git` does, probably because `GIT_SSH_COMMAND='ssh -i ~/..ssh/gerrit-key'` was implemented only in `git 2.3.0`.

Still, configuring the user and private key in Gerrit Trigger works, on the same Jenkins master, so something is done differently by `gerrit-plugin`.

I do mention that I configured Jenkins private key credentials with the same key that works from CLI for the plugin, but still it fails to connect giving a:
```
[Wed Jan 03 18:56:03 UTC 2018] Starting branch indexing...
Creating git repository in /var/lib/jenkins/caches/git-8c5248766cc2421c7b593787b5fb6a92
 > git init /var/lib/jenkins/caches/git-8c5248766cc2421c7b593787b5fb6a92 # timeout=10
Setting origin to ssh://gerrit-service-account@gerrit.example.com/foo.git
 > git config remote.origin.url ssh://gerrit-service-account@gerrit.example.com/foo.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
using GIT_SSH to set credentials gerrit-service-account private key
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* +refs/changes/*:refs/remotes/origin/*
ERROR: [Wed Jan 03 18:56:04 UTC 2018] Could not update folder level actions from source f2a102e5-dcbb-42ec-8733-51eadbadca9a
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* +refs/changes/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Warning: Permanently added 'gerrit.example.com' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1689)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:380)
	at jenkins.plugins.gerrit.AbstractGerritSCMSource.doRetrieve(AbstractGerritSCMSource.java:454)
	at jenkins.plugins.gerrit.AbstractGerritSCMSource.retrieveActions(AbstractGerritSCMSource.java:159)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:746)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:591)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1004)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
[Wed Jan 03 18:56:04 UTC 2018] Finished branch indexing. Indexing took 0.43 sec
FATAL: Failed to recompute children of foo
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* +refs/changes/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Warning: Permanently added 'gerrit.example.com' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1689)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:380)
	at jenkins.plugins.gerrit.AbstractGerritSCMSource.doRetrieve(AbstractGerritSCMSource.java:454)
	at jenkins.plugins.gerrit.AbstractGerritSCMSource.retrieveActions(AbstractGerritSCMSource.java:159)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:746)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:591)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1004)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finished: FAILURE
```

I know that this sounds like a user specific problem, but requiring such a new version of git would cause problems for users. For example latest version of git on RHEL 7.x is just 1.8.3.1.

**Comment by lucamilanesio** [comment]
@ssbarnea thank you for trying the pre-Alpha 0.1.0 version :-) Feedback is more than appreciated, especially early on like now.

I have to confess that this first pre-Alpha has been tested with Git/HTTP only and not with SSH public key credentials.

Will remember to keep RHEL 7.x and Git 1.8.x in my validation tests to make sure that works as expected.

**Comment by lucamilanesio** [comment]
__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
